### ISSUE TITLE
BiobankGeo.py gives incorrect error; '11.57549 '  has to be '11.57549' 

### ISSUE THREAD

**Issue by Fernananas** [BBMRI-ERIC/directory-scripts#17]
Validation script gives following error: Invalid biobank longitude (should be a decimal number without any spaces or stray characters around - the surrounding quotes are added in this report): '11.57549 '

Looking in the Directory there is no spacing at the end, when looking in the database the spacing is not visible.

**Comment by esthervanenckevort** [comment]
For which biobank was this reported?

**Comment by holubp** [comment]
Very likely the problem was caused by data quality checks using old data - the data quality checks support caching and for full runs, one should purge the directory cache at least. I examined some older cache and indeed it contained spaces around 11.57549. Current data, however, does not contain any spaces. 

The report was, I assume, for bbmri-eric:ID:DE_ASK-Tx.

**Comment by esthervanenckevort** [comment]
Not a bug, but good manner to reset the cache for a report (which kind of defeats the purpose of the cache)
